{{- if include "renovate-scheduler.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "renovate-scheduler.secretName" . }}
  labels:
    {{- include "renovate-scheduler.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.scheduler.secretData }}
  {{- toYaml .Values.scheduler.secretData | nindent 2 }}
  {{- else }}
  RENOVATE_TOKEN: ""
  {{- end }}
{{- end }}
